### ISSUE TITLE
Get error "Repostitory structure for master is not compliant" with HACS 1.15.2 and Home Assistant 2021.10.0

### ISSUE THREAD

**Issue by tioan** [Sebclem/sebclem-hassio-addon-repository#30]
<html>
<body>
<h2 id="title" class="mdc-dialog__title" style="display: block; -webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-headline6-font-size, 1.25rem); line-height: var(--mdc-typography-headline6-line-height, 2rem); font-weight: var(--mdc-typography-headline6-font-weight, 500); letter-spacing: var(--mdc-typography-headline6-letter-spacing, 0.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration, inherit); text-transform: var(--mdc-typography-headline6-text-transform, inherit); position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 0px 24px 9px; color: var(--mdc-dialog-heading-ink-color, rgba(0, 0, 0, 0.87));">Home Assistant Community Store</h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: 14px; line-height: var(--mdc-typography-body1-line-height, 1.5rem); font-weight: 400; letter-spacing: var(--mdc-typography-body1-letter-spacing, 0.03125em); text-decoration-line: ; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-transform: none; flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: rgb(225, 225, 225); padding: var(--dialog-content-padding, 20px 24px); position: var(--dialog-content-position, relative); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><p class="" style="margin: 0px; padding-top: 6px; padding-bottom: 24px; color: var(--primary-text-color);"><div class="markdown-body" style="text-size-adjust: 100%; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; line-height: 1.5; overflow-wrap: break-word;">

Integration version: | 1.15.2
-- | --
Frontend version: | 20210822172723

</div></p></div></slot></div>
</body>
</html>

![image](https://user-images.githubusercontent.com/259990/137636818-413ecbe2-b246-4011-a844-35b76b16c6e6.png)

**Comment by Sebclem** [comment]
This is not a hac repository, this is a add-on repository for supervised Home Assistant (This is non an integration but a add-on)

**Comment by Sebclem** [comment]
See this: https://home-assistant.io/hassio/installing_third_party_addons/
