### ISSUE TITLE
Fail to upload snapshot to nextcloud (HTTPError: Response code 413 (Request Entity Too Large)) !

### ISSUE THREAD

**Issue by MiGro1194** [Sebclem/sebclem-hassio-addon-repository#47]
Hi,

my HomeAssistant installation is correspondingly large and unfortunately I cannot make a backup of it via the addon.

I don't currently know what information would still be relevant for troubleshooting.

Best regards,
Michael

**Comment by Sebclem** [comment]
Please check https://github.com/Sebclem/hassio-nextcloud-backup/issues/9
