### ISSUE TITLE
Can't add repository

### ISSUE THREAD

**Issue by simon-mueller** [Sebclem/sebclem-hassio-addon-repository#48]
Hi,
I'm trying to add the repository to my HAOS instance and getting this error message:

> https://github.com/Sebclem/hassio-nextcloud-backup.git is not a valid add-on repository

Core 2024.8.1
Supervisor 2024.08.0
Operating System 13.0

**Comment by simon-mueller** [comment]
Nvm, I used this repository to add.

**Comment by Sebclem** [comment]
You are using the wrong repo as repository: 
https://github.com/Sebclem/sebclem-hassio-addon-repository?tab=readme-ov-file#installation

You need to use this one: https://github.com/Sebclem/sebclem-hassio-addon-repository
